component: scf
name: yanzhipingfen-face-proxy

inputs:
  name: yanzhipingfen-face-proxy
  src: ./
  handler: tencent-cloud-function.main_handler
  runtime: Nodejs18.15
  region: ap-guangzhou
  memorySize: 128
  timeout: 20
  environment:
    variables:
      BAIDU_API_KEY: ${env:BAIDU_API_KEY}
      BAIDU_SECRET_KEY: ${env:BAIDU_SECRET_KEY}
      ALIYUN_ACCESS_KEY_ID: ${env:ALIYUN_ACCESS_KEY_ID}
      ALIYUN_ACCESS_KEY_SECRET: ${env:ALIYUN_ACCESS_KEY_SECRET}
      ALIYUN_OSS_BUCKET: ${env:ALIYUN_OSS_BUCKET}
      ALIYUN_OSS_REGION: ${env:ALIYUN_OSS_REGION}
      ALIYUN_OSS_PREFIX: ${env:ALIYUN_OSS_PREFIX}
  events:
    - http:
        parameters:
          netConfig:
            enableIntranet: false
            enableExtranet: true
          qualifier: $DEFAULT
          authType: NONE
