component: scf
name: yanzhipingfen-face-proxy

inputs:
  name: yanzhipingfen-face-proxy
  src: ./
  handler: tencent-cloud-function.main_handler
  runtime: Nodejs18.15
  region: ap-guangzhou
  memorySize: 128
  timeout: 20
  environment:
    variables:
      BAIDU_API_KEY: ${env:BAIDU_API_KEY}
      BAIDU_SECRET_KEY: ${env:BAIDU_SECRET_KEY}
      TIANAPI_KEY: ${env:TIANAPI_KEY}
  events:
    - http:
        parameters:
          netConfig:
            enableIntranet: false
            enableExtranet: true
          qualifier: $DEFAULT
          authType: NONE
